networks:
  default:

services:
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - default

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  log:
    build: services/log
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKER_URL=kafka
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - kafka

  mastodon:
    build: services/mastodon
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKER_URL: kafka
      MONGO_URL: mongo
      MONGO_USER: root
      MONGO_PASS: example
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - kafka
      - mongo

volumes:
  kafka_data:
