name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-mastodon:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/mastodon
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: |
             services/mastodon/go.sum
             
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
  build-log:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./services/log
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: |
             services/log/go.sum
  
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: go test -v ./...
